# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7e4feeb7bfb607c38f5a1b84bb50bb7696c160430a0713fd42a101ceba53d7499a67da79e5e7fafef3db5f9dc389517b2280886e4f60ce9188ae63201167a9

test:
  secret_key_base: 29f3ca7562a1f8158c969ed2a160a4b392769a3d09afd8b96c7def844afbcaa8c9125a76b2f672dae1a74a44595510e2af13652b87c2b32499a37b451e9a5e24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
